#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"; TMP="$(mktemp -d)"; trap 'rm -rf "$TMP"' EXIT; POLICY="$TMP/policy.json"
node - "$ROOT" "$POLICY" <<'NODE'
const fs = require("fs"); const root = process.argv[2]; const output = process.argv[3];
(async () => { const { policyDigest } = await import(`${root}/scripts/lib/maintenance-policy-contract.mjs`); const p = JSON.parse(fs.readFileSync(`${root}/tests/fixtures/maintenance-policy/normal-window.json`, "utf8")).records.find((x) => x.kind === "maintenance-policy"); p.window.days_of_week=["sun"]; p.window.start_local_time="01:30"; p.window.duration="PT2H"; p.timezone="Europe/Stockholm"; p.dst_policy={nonexistent_time:"shift_forward_to_next_valid",ambiguous_time:"use_first_instant"}; delete p.policy_digest; p.policy_digest=policyDigest(p); fs.writeFileSync(output, JSON.stringify(p)); })();
NODE
cat >"$TMP/test.mjs" <<NODE
import fs from "node:fs"; import assert from "node:assert/strict"; import { inspectController, orderTargets, runController, windowStatus } from "${ROOT}/scripts/maintenance-controller.mjs";
const policy=JSON.parse(fs.readFileSync("${POLICY}","utf8")), dir="${TMP}/state", now="2026-10-25T00:45:00Z";
assert.equal(windowStatus(policy,Date.parse(now)).eligible,true,"fold first instant open"); const gap=structuredClone(policy); gap.window.start_local_time="02:30"; gap.dst_policy.nonexistent_time="fail_closed"; assert.equal(windowStatus(gap,Date.parse("2026-03-29T01:00:00Z")).eligible,false,"DST gap fails closed");
assert.deepEqual(orderTargets([{node_id:"b",depends_on:["a"]},{node_id:"a",depends_on:[]}]),["a","b"]); let executions=0; const run=()=>runController({policy,nodeId:"node-a",stateDir:dir,now,executor:()=>{executions++;return"x".repeat(2048);}}); assert.equal(run().ran,true); assert.equal(executions,1); assert.equal(run().reason,"already_completed_occurrence"); assert.equal(executions,1,"success cannot repeat in same occurrence"); assert.equal(JSON.parse(fs.readFileSync(dir+"/state.json")).nodes["node-a"].result.length,512,"success output is bounded"); assert.equal(runController({policy,nodeId:"node-a",stateDir:dir,now:"2026-11-01T01:00:00Z",executor:()=>{executions++;return"next";}}).ran,true,"future occurrence is admitted"); assert.equal(executions,2);
let temporalState=JSON.parse(fs.readFileSync(dir+"/state.json")); temporalState.nodes.overdue={status:"idle",missed_occurrences:3,first_deferred_at:"2026-10-18T00:45:00Z"}; fs.writeFileSync(dir+"/state.json",JSON.stringify(temporalState)); const overdue=inspectController({policy,nodeId:"overdue",stateDir:dir,now}); assert.equal(overdue.temporal.overdue,true,"missed/overdue state is explicit"); assert.equal(overdue.eligible,false,"overdue escalation cannot authorize mutation");
const stateFile=dir+"/state.json", state=JSON.parse(fs.readFileSync(stateFile)); state.nodes["node-a"].status="in_flight"; fs.writeFileSync(stateFile,JSON.stringify(state)); assert.equal(run().reason,"in_flight_requires_operator_recovery"); assert.equal(executions,2,"restart cannot duplicate executor");
fs.writeFileSync(dir+"/hold.json",JSON.stringify({active:true})); assert.equal(run().reason,"held"); fs.writeFileSync(dir+"/hold.json",JSON.stringify({active:false})); assert.equal(inspectController({policy,nodeId:"node-a",stateDir:dir,now,clock:"unsynchronized"}).reason,"clock_uncertain"); const heldAtBoundary=runController({policy,nodeId:"boundary",stateDir:dir,now,beforeMutation:()=>fs.writeFileSync(dir+"/hold.json",JSON.stringify({active:true})),executor:()=>{throw Error("must not run")}}); assert.equal(heldAtBoundary.reason,"held_before_mutation"); fs.writeFileSync(dir+"/hold.json",JSON.stringify({active:false}));
fs.mkdirSync(dir+"/locks",{recursive:true}); fs.writeFileSync(dir+"/locks/node-b.lock","{}"); assert.equal(runController({policy,nodeId:"node-b",stateDir:dir,now,executor:()=>{throw Error("must not run")}}).reason,"lock_contended");
const retryDir="${TMP}/retry", bad=()=>runController({policy,nodeId:"retry",stateDir:retryDir,now,executor:()=>{throw Error("no")}}); assert.equal(bad().reason,"retry_pending"); assert.equal(bad().reason,"retry_backoff"); let retry=JSON.parse(fs.readFileSync(retryDir+"/state.json")); retry.nodes.retry.next_eligible_at=now; fs.writeFileSync(retryDir+"/state.json",JSON.stringify(retry)); assert.equal(bad().reason,"retry_pending"); retry=JSON.parse(fs.readFileSync(retryDir+"/state.json")); retry.nodes.retry.next_eligible_at=now; fs.writeFileSync(retryDir+"/state.json",JSON.stringify(retry)); assert.equal(bad().reason,"retry_exhausted"); retry=JSON.parse(fs.readFileSync(retryDir+"/state.json")); retry.nodes.retry.next_eligible_at=now; fs.writeFileSync(retryDir+"/state.json",JSON.stringify(retry)); assert.equal(bad().reason,"retry_exhausted","terminal retry cannot reopen after backoff");
const interleaveDir="${TMP}/interleave"; const a=runController({policy,nodeId:"node-c",stateDir:interleaveDir,now,beforeMutation:()=>assert.equal(runController({policy,nodeId:"node-d",stateDir:interleaveDir,now,executor:()=>"d"}).ran,true),executor:()=>"c"}); assert.equal(a.ran,true); const merged=JSON.parse(fs.readFileSync(interleaveDir+"/state.json")); assert.equal(merged.nodes["node-c"].status,"succeeded"); assert.equal(merged.nodes["node-d"].status,"succeeded","interleaved node update is preserved");
const finalSuccessDir="${TMP}/final-success", holdFinalize=(d)=>()=>{fs.mkdirSync(d,{recursive:true});fs.writeFileSync(d+"/state.lock","{}",{flag:"wx"});}; const finalSuccess=runController({policy,nodeId:"node-e",stateDir:finalSuccessDir,now,beforeFinalize:holdFinalize(finalSuccessDir),executor:()=>"ran"}); assert.deepEqual(finalSuccess,{ran:true,reason:"finalization_failed_operator_recovery"}); assert.equal(JSON.parse(fs.readFileSync(finalSuccessDir+"/state.json")).nodes["node-e"].status,"in_flight","unfinalized success remains fail-closed");
const finalErrorDir="${TMP}/final-error", finalError=runController({policy,nodeId:"node-f",stateDir:finalErrorDir,now,beforeFinalize:holdFinalize(finalErrorDir),executor:()=>{throw Error("failed")}}); assert.deepEqual(finalError,{ran:false,reason:"finalization_failed_operator_recovery"}); assert.equal(JSON.parse(fs.readFileSync(finalErrorDir+"/state.json")).nodes["node-f"].status,"in_flight","unfinalized error never claims retry");
assert.throws(()=>inspectController({policy,nodeId:"../escape",stateDir:dir,now}),/canonical/); const tampered=structuredClone(policy); tampered.policy_digest="sha256:"+"0".repeat(64); assert.throws(()=>runController({policy:tampered,nodeId:"safe-node",stateDir:dir,now,executor:()=>"no"}),/digest/); console.log("maintenance controller: DST, hold, locks, crash, retry, clock OK");
NODE
node "$TMP/test.mjs"
